typography_spectrum: 0.8764875826891512
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5
  lightness: 0.184286990435794
  saturation: 0
  rhythmicContrast: 0.874820333905518
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d17c515c-f9f6-4c66-9a6f-901aca5b33e2.jpg
name: 'LORE • Dream Rock • Lancaster, PA'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
purpose: []
